name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Verify build artifacts
        run: |
          echo "Checking dist directory contents..."
          ls -la dist/

          # Verify expected files exist
          if [ ! -f "dist/Traktor-Z1-MK2.script.js" ]; then
            echo "❌ Missing Traktor-Z1-MK2.script.js"
            exit 1
          fi

          if [ ! -f "dist/Traktor Z1 MK2.hid.xml" ]; then
            echo "❌ Missing Traktor Z1 MK2.hid.xml"
            exit 1
          fi

          echo "✅ All expected build artifacts found"

          # Show file sizes
          echo "Build artifact sizes:"
          du -h dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mixxx-traktor-z1-mk2-build
          path: dist/
          retention-days: 30
