name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Verify build artifacts
        run: |
          ls -la dist/
          echo "Built files:"
          find dist/ -type f -name "*.js" -o -name "*.xml"

      - name: Create release archive
        run: |
          cd dist
          zip -r ../infinifox-mixxx-traktor-controller-mappings.zip .
          cd ..

      - name: Get tag name
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Infinifox Mixxx Traktor Controller Mappings ${{ steps.tag.outputs.tag_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            infinifox-mixxx-traktor-controller-mappings.zip
            dist/Traktor-Z1-MK2.script.js
            dist/Traktor Z1 MK2.hid.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
